"""Add genre, rating, and duration to BlogPost

Revision ID: a7af5eb241f9
Revises: d8d2a0cb6dab
Create Date: 2024-10-22 15:42:18.123312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7af5eb241f9'
down_revision = 'd8d2a0cb6dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=False, server_default='Blogpost'))  # Setting a default genre
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True, server_default='0'))  # Setting a default rating
        batch_op.add_column(sa.Column('duration', sa.String(length=250), nullable=True, server_default='0'))  # Setting a default duration

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('rating')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
